### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ASalihov** [Wintegra/Wintegra.Data#1]
Hi. I've got error by com.ibm.db2.jcc.am.tf while opening connection:

Не удалось привести тип объекта \"java.util.PropertyResourceBundle\" к типу \"sun.util.resources.OpenListResourceBundle\

How  can I fix it?

**Comment by Wintegra** [comment]
"com.ibm.db2.jcc.am.tf" part of the JDBC IBM driver

When you are experiencing this error?
Are automated test pass?
